version: '3.8'

services:
  backend:
    image: demo-app-backend
    build: .
    container_name: springboot-app
    ports:
      - "8085:8085"
#    depends_on:
#     - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://10.0.3.69:27017/demo_db
    networks:
      - app-network

#  mongodb:
#    image: mongo:7
#   container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_DATABASE: demo_db
#    networks:
#      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "9095:80"
    volumes:
       - ./nginx/:/etc/nginx/:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

